USE [SALEGEARVN]
GO

-- 1. QUYENHAN
IF NOT EXISTS (SELECT TOP 1 1 FROM QUYENHAN)
BEGIN
    INSERT INTO QUYENHAN (TENQUYEN, GHICHU) VALUES (N'Administrator', N'Quản trị viên toàn quyền');
    INSERT INTO QUYENHAN (TENQUYEN, GHICHU) VALUES (N'Kế toán', N'Nhân viên kế toán');
    INSERT INTO QUYENHAN (TENQUYEN, GHICHU) VALUES (N'Nhân viên Kho', N'Nhân viên quản lý kho');
    INSERT INTO QUYENHAN (TENQUYEN, GHICHU) VALUES (N'Nhân viên Kinh doanh', N'Nhân viên bán hàng');
END
GO

-- 2. NGUOIDUNG (Default Pass: 123456)
IF NOT EXISTS (SELECT TOP 1 1 FROM NGUOIDUNG WHERE TAIKHOAN = 'admin')
BEGIN
    DECLARE @MaQuyenAdmin INT = (SELECT TOP 1 MAQUYEN FROM QUYENHAN WHERE TENQUYEN = N'Administrator');
    INSERT INTO NGUOIDUNG (TAIKHOAN, MATKHAU, MAQUYEN, HOTEN, HOATDONG, MANV) 
    VALUES ('admin', '123456', @MaQuyenAdmin, N'Quản Trị Viên', 1, NULL);
END
GO

-- 3. DM_NHOMHANG
IF NOT EXISTS (SELECT TOP 1 1 FROM DM_NHOMHANG)
BEGIN
    INSERT INTO DM_NHOMHANG (MANHOM, TENNHOM) VALUES ('DT', N'Điện thoại');
    INSERT INTO DM_NHOMHANG (MANHOM, TENNHOM) VALUES ('LT', N'Laptop');
    INSERT INTO DM_NHOMHANG (MANHOM, TENNHOM) VALUES ('PK', N'Phụ kiện');
END
GO

-- 4. DM_HANGHOA
IF NOT EXISTS (SELECT TOP 1 1 FROM DM_HANGHOA)
BEGIN
    INSERT INTO DM_HANGHOA (MAHH, MANHOM, TENHH, DVT, GIAVON, GIABAN, TONKHO, ACTIVE)
    VALUES ('IP15', 'DT', N'iPhone 15 Pro Max 256GB', N'Cái', 28000000, 32000000, 10, 1);
    
    INSERT INTO DM_HANGHOA (MAHH, MANHOM, TENHH, DVT, GIAVON, GIABAN, TONKHO, ACTIVE)
    VALUES ('DELLXPS', 'LT', N'Dell XPS 13 9310', N'Cái', 35000000, 40000000, 5, 1);
    
    INSERT INTO DM_HANGHOA (MAHH, MANHOM, TENHH, DVT, GIAVON, GIABAN, TONKHO, ACTIVE)
    VALUES ('MOUSE', 'PK', N'Chuột Logitech MX Master 3', N'Cái', 2000000, 2500000, 20, 1);
END
GO

-- 5. DANHMUCKHACHHANG
IF NOT EXISTS (SELECT TOP 1 1 FROM DANHMUCKHACHHANG)
BEGIN
    INSERT INTO DANHMUCKHACHHANG (MAKH, TENKH, DIACHI, SDT, EMAIL)
    VALUES ('KHLE', N'Khách lẻ', N'Tại cửa hàng', '', '');
    
    INSERT INTO DANHMUCKHACHHANG (MAKH, TENKH, DIACHI, SDT, EMAIL)
    VALUES ('KH001', N'Nguyễn Văn A', N'123 Lê Lợi, TP.HCM', '0909123456', 'nva@email.com');
END
GO

-- 6. DM_NHACUNGCAP
IF NOT EXISTS (SELECT TOP 1 1 FROM DM_NHACUNGCAP)
BEGIN
    INSERT INTO DM_NHACUNGCAP (MA_NCC, TEN_NCC, DIACHI_NCC, SDT)
    VALUES ('NCC01', N'Công ty FPT Trading', N'Khu CNC, Q9', '02812345678');
END
GO
