-- Check and Insert Account 131 (Phải thu khách hàng)
IF NOT EXISTS (SELECT 1 FROM DM_TAIKHOANKETOAN WHERE SO_TK = '131')
BEGIN
    INSERT INTO DM_TAIKHOANKETOAN (SO_TK, TEN_TK, TINH_CHAT) VALUES ('131', N'Phải thu khách hàng', N'Dư Nợ');
END

-- Check and Insert Account 511 (Doanh thu bán hàng)
IF NOT EXISTS (SELECT 1 FROM DM_TAIKHOANKETOAN WHERE SO_TK = '511')
BEGIN
    INSERT INTO DM_TAIKHOANKETOAN (SO_TK, TEN_TK, TINH_CHAT) VALUES ('511', N'Doanh thu bán hàng', N'Dư Có');
END

-- Check and Insert Account 632 (Giá vốn hàng bán)
IF NOT EXISTS (SELECT 1 FROM DM_TAIKHOANKETOAN WHERE SO_TK = '632')
BEGIN
    INSERT INTO DM_TAIKHOANKETOAN (SO_TK, TEN_TK, TINH_CHAT) VALUES ('632', N'Giá vốn hàng bán', N'Dư Nợ');
END

-- Check and Insert Account 1111 (Tiền mặt)
IF NOT EXISTS (SELECT 1 FROM DM_TAIKHOANKETOAN WHERE SO_TK = '1111')
BEGIN
    INSERT INTO DM_TAIKHOANKETOAN (SO_TK, TEN_TK, TINH_CHAT) VALUES ('1111', N'Tiền mặt Việt Nam', N'Dư Nợ');
END

-- Check and Insert Account 156 (Hàng hóa)
IF NOT EXISTS (SELECT 1 FROM DM_TAIKHOANKETOAN WHERE SO_TK = '156')
BEGIN
    INSERT INTO DM_TAIKHOANKETOAN (SO_TK, TEN_TK, TINH_CHAT) VALUES ('156', N'Hàng hóa', N'Dư Nợ');
END
